attempting to fix sed error for CD.yml

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -111,6 +111,7 @@ jobs:
           ls -al
           mkdir -p artifacts
           tar -czvf artifacts/zhub-build-${{ github.run_number }}.tar.gz --exclude='artifacts' --exclude='.git*' -C . .
+          file artifacts/zhub-build-${{ github.run_number }}.tar.gz
           if [ "${{ github.event.inputs.version }}" ]; then
             cp artifacts/zhub-build-${{ github.run_number }}.tar.gz artifacts/zhub-release-${{ github.event.inputs.version }}.tar.gz
           fi
@@ -157,6 +158,22 @@ jobs:
           # Fetch the existing gh-pages branch
           git fetch --depth=1 origin gh-pages
           git checkout gh-pages
+          
+          if [ -f index.html ]; then
+            echo "index.html found"
+          else
+            echo "index.html not found"
+            exit 1
+          fi
+          
+          if [ -f template.html ]; then
+            echo "template.html found"
+          else
+            echo "template.html not found"
+            exit 1
+          fi
+          
+          cp -f template.html index.html
 
           mkdir -p downloads/latest
 
@@ -169,16 +186,8 @@ jobs:
             ln -sf ../zhub-release-${{ github.event.inputs.version }}.tar.gz ./downloads/latest/release
           fi
 
-          build_links=$(for f in downloads/*build*.tar.gz; do echo "<li><a href=\"$f\">$(basename "$f")</a></li>"; done | tr '\n' ' ')
-          release_links=$(for f in downloads/*release*.tar.gz; do echo "<li><a href=\"$f\">$(basename "$f")</a></li>"; done | tr '\n' ' ')
-
-          if [ -f index.html ]; then
-          echo "index.html found"
-          else
-            echo "index.html not found"
-            exit 1
-          fi
-          
+          build_links=$(for f in $(ls -t downloads/*build*.tar.gz); do echo "<li><a href=\"$f\">$(basename "$f")</a></li>"; done | tr '\n' ' ')
+          release_links=$(for f in $(ls -t downloads/*release*.tar.gz); do echo "<li><a href=\"$f\">$(basename "$f")</a></li>"; done | tr '\n' ' ')
           # Update the file using sed
           sed -i 's|<!-- CD BUILDS HERE -->|'"$build_links"'|' index.html
           sed -i 's|<!-- CD RELEASES HERE -->|'"$release_links"'|' index.html
